<!DOCTYPE html>
<html>
<head>
    

    

    



    <meta charset="utf-8">
    
    
    
    
    <title>Go 错误处理指北：Error vs Exception vs ErrNo | 江湖十年 | 学而不思则罔，思而不学则殆。</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <meta name="theme-color" content="#3F51B5">
    
    
    <meta name="keywords" content="Go,Error">
    <meta name="description" content="很多有其他编程语言经验的人初次接触 Go 语言时，想必对 if err !&#x3D; nil 的错误处理方式感到新奇，之后用久了，竟发现有点令人抓狂。 因为很多人不满 Go 语言的错误处理方式，甚至有人做了一张梗图：   哈哈😄，不吹不黑，本文就来对比下 Python、C 以及 Go 这三种编程语言中的异常处理机制，看看你更喜欢哪一种。">
<meta property="og:type" content="article">
<meta property="og:title" content="Go 错误处理指北：Error vs Exception vs ErrNo">
<meta property="og:url" content="http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/index.html">
<meta property="og:site_name" content="江湖十年">
<meta property="og:description" content="很多有其他编程语言经验的人初次接触 Go 语言时，想必对 if err !&#x3D; nil 的错误处理方式感到新奇，之后用久了，竟发现有点令人抓狂。 因为很多人不满 Go 语言的错误处理方式，甚至有人做了一张梗图：   哈哈😄，不吹不黑，本文就来对比下 Python、C 以及 Go 这三种编程语言中的异常处理机制，看看你更喜欢哪一种。">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/err.png">
<meta property="article:published_time" content="2024-09-06T12:38:36.000Z">
<meta property="article:modified_time" content="2025-09-11T06:46:31.629Z">
<meta property="article:author" content="江湖十年">
<meta property="article:tag" content="Go">
<meta property="article:tag" content="Error">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/err.png">
    
        <link rel="alternate" type="application/atom+xml" title="江湖十年" href="/atom.xml">
    
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="stylesheet" href="//unpkg.com/hexo-theme-material-indigo@latest/css/style.css">
    <script>window.lazyScripts=[]</script>

    <!-- custom head -->
    

<meta name="generator" content="Hexo 4.2.0"></head>

<body>
    <div id="loading" class="active"></div>

    <aside id="menu" class="hide" >
  <div class="inner flex-row-vertical">
    <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="menu-off">
        <i class="icon icon-lg icon-close"></i>
    </a>
    <div class="brand-wrap" style="background-image:url(/img/brand.jpg)">
      <div class="brand">
        <a href="/" class="avatar waves-effect waves-circle waves-light">
          <img src="/img/avatar.png">
        </a>
        <hgroup class="introduce">
          <h5 class="nickname">江湖十年</h5>
          <a href="mailto:jianghushinian007@outlook.com" title="jianghushinian007@outlook.com" class="mail">jianghushinian007@outlook.com</a>
        </hgroup>
      </div>
    </div>
    <div class="scroll-wrap flex-col">
      <ul class="nav">
        
            <li class="waves-block waves-effect">
              <a href="/"  >
                <i class="icon icon-lg icon-home"></i>
                主页
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/archives"  >
                <i class="icon icon-lg icon-archives"></i>
                归档
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/tags"  >
                <i class="icon icon-lg icon-tags"></i>
                标签
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/categories"  >
                <i class="icon icon-lg icon-th-list"></i>
                分类
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/about"  >
                <i class="icon icon-lg icon-link"></i>
                关于
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="https://github.com/jianghushinian" target="_blank" >
                <i class="icon icon-lg icon-github"></i>
                Github
              </a>
            </li>
        
      </ul>
    </div>
  </div>
</aside>

    <main id="main">
        <header class="top-header" id="header">
    <div class="flex-row">
        <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light on" id="menu-toggle">
          <i class="icon icon-lg icon-navicon"></i>
        </a>
        <div class="flex-col header-title ellipsis">Go 错误处理指北：Error vs Exception vs ErrNo</div>
        
        <div class="search-wrap" id="search-wrap">
            <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="back">
                <i class="icon icon-lg icon-chevron-left"></i>
            </a>
            <input type="text" id="key" class="search-input" autocomplete="off" placeholder="输入感兴趣的关键字">
            <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="search">
                <i class="icon icon-lg icon-search"></i>
            </a>
        </div>
        
        
        <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="menuShare">
            <i class="icon icon-lg icon-share-alt"></i>
        </a>
        
    </div>
</header>
<header class="content-header post-header">

    <div class="container fade-scale">
        <h1 class="title">Go 错误处理指北：Error vs Exception vs ErrNo</h1>
        <h5 class="subtitle">
            
                <time datetime="2024-09-06T12:38:36.000Z" itemprop="datePublished" class="page-time">
  2024-09-06
</time>


	<ul class="article-category-list"><li class="article-category-list-item"><a class="article-category-list-link" href="/categories/Go/">Go</a></li></ul>

            
        </h5>
    </div>

    


</header>


<div class="container body-wrap">
    
    <aside class="post-widget">
        <nav class="post-toc-wrap post-toc-shrink" id="post-toc">
            <h4>TOC</h4>
            <ol class="post-toc"><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#Python-错误处理"><span class="post-toc-number">1.</span> <span class="post-toc-text">Python 错误处理</span></a></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#C-错误处理"><span class="post-toc-number">2.</span> <span class="post-toc-text">C 错误处理</span></a></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#Go-错误处理"><span class="post-toc-number">3.</span> <span class="post-toc-text">Go 错误处理</span></a></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#总结"><span class="post-toc-number">4.</span> <span class="post-toc-text">总结</span></a></li></ol>
        </nav>
    </aside>


<article id="post-go-error-guidelines-error-exception-errno"
  class="post-article article-type-post fade" itemprop="blogPost">

    <div class="post-card">
        <h1 class="post-card-title">Go 错误处理指北：Error vs Exception vs ErrNo</h1>
        <div class="post-meta">
            <time class="post-time" title="2024-09-06 20:38:36" datetime="2024-09-06T12:38:36.000Z"  itemprop="datePublished">2024-09-06</time>

            
	<ul class="article-category-list"><li class="article-category-list-item"><a class="article-category-list-link" href="/categories/Go/">Go</a></li></ul>



            
<span id="busuanzi_container_page_pv" title="文章总阅读量" style='display:none'>
    <i class="icon icon-eye icon-pr"></i><span id="busuanzi_value_page_pv"></span>
</span>


        </div>
        <div class="post-content" id="post-content" itemprop="postContent">
            <p>很多有其他编程语言经验的人初次接触 Go 语言时，想必对 <code>if err != nil</code> 的错误处理方式感到新奇，之后用久了，竟发现有点令人抓狂。</p>
<p>因为很多人不满 Go 语言的错误处理方式，甚至有人做了一张梗图：</p>
<div style="text-align: center"><img src="err.png" alt="if err != nil" style="zoom:50%;" /></div>

<p>哈哈😄，不吹不黑，本文就来对比下 Python、C 以及 Go 这三种编程语言中的异常处理机制，看看你更喜欢哪一种。</p>
<a id="more"></a>

<h3 id="Python-错误处理"><a href="#Python-错误处理" class="headerlink" title="Python 错误处理"></a>Python 错误处理</h3><p>因为我接触的第一门编程语言是 Python，所以我就先讲讲 Python 中的错误处理机制。</p>
<p>Python 的错误处理机制与 Java、C#、JavaScript 等主流的高级编程语言非常类似，它们都可以算做是 Exception 派系。</p>
<p>以下是 Python 错误处理的典型示例程序：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">div</span><span class="params">(a, b)</span>:</span></span><br><span class="line">    <span class="keyword">return</span> a / b</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    result = div(<span class="number">1</span>, <span class="number">0</span>)</span><br><span class="line">    print(result)</span><br><span class="line"><span class="keyword">except</span> ZeroDivisionError <span class="keyword">as</span> e:</span><br><span class="line">    logging.error(e)</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    logging.error(e)</span><br></pre></td></tr></table></figure>

<p><code>div</code> 函数内部不对参数进行任何校验，当除数 <code>b</code> 为 <code>0</code> 时，代码会抛出 <code>ZeroDivisionError</code> 错误。</p>
<p>我们在函数调用处使用 <code>try...except...</code> 语句对错误进行捕获并处理。捕获到 <code>ZeroDivisionError</code> 表示遇到除数为 <code>0</code> 的情况，而捕获到 <code>Exception</code> 则为了避免放过出现其他未知的异常。</p>
<p>从这两个错误的命名来看：<code>ZeroDivisionError</code> 和 <code>Exception</code>，一个表示「错误」，一个表示「异常」。其实它们都继承自 <code>BaseException</code> 基类，在 Python 中并不区分错误和异常，所以 Python 中的错误处理，我们一般称为异常处理。所有 Exception 派系的编程语言也都类似。</p>
<p>除了内置异常，我们也可以很方便的定义自己的异常类：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    ...</span><br></pre></td></tr></table></figure>

<p>没错，就是这么简单。</p>
<p>可以按照如下方式使用自定义异常：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">raise</span> MyException(<span class="string">"my custom exception"</span>)</span><br></pre></td></tr></table></figure>

<p>这与内置异常没什么两样，<code>try...except...</code> 同样能够正常捕获自定义异常。</p>
<p>其实这种 <code>try...except...</code> 方式处理异常，最大的好处就是：<strong>异常兜底</strong>。</p>
<p>在一整个代码块中间，无论写了多少行代码，无论哪里可能出现异常，我们都可以放心大胆的不去处理异常，而是在代码块最外层使用 <code>try...except...</code> 进行捕获，示例如下：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">a</span><span class="params">()</span>:</span></span><br><span class="line">    ...</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">b</span><span class="params">()</span>:</span></span><br><span class="line">    ...</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">c</span><span class="params">()</span>:</span></span><br><span class="line">    ...</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">main</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        a()</span><br><span class="line">        b()</span><br><span class="line">        c()</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        logging.error(e)</span><br><span class="line">    <span class="keyword">else</span>:</span><br><span class="line">        print(<span class="string">"success"</span>)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">"release resources"</span>)</span><br></pre></td></tr></table></figure>

<p>这种方式极大的简化了我们的代码编写，不用在每一个函数调用处都对异常进行处理，仅需要在最外层做一次异常处理即可。</p>
<p>当然，这种方式也有弊端，那就是异常不再是异常。什么意思？就是说，在 Python 中的异常其实是不分轻重的，有些异常可以忽略，有些异常又不可以忽略，但上面的示例代码显然无法区分异常的严重程度。</p>
<p>并且，因为有异常兜底，很多开发者写代码的时候就会更加随性，写出来的程序就会更加不可控。</p>
<p>接下来，我们再看一看 C 语言中的错误处理。</p>
<h3 id="C-错误处理"><a href="#C-错误处理" class="headerlink" title="C 错误处理"></a>C 错误处理</h3><p>虽然我在工作中没怎么写过 C，但 C 乃“万物鼻祖”。既然要对比多种编程语言错误处理机制，C 自然必不可少。</p>
<p>其实 C 语言并没有提供对错误处理的直接支持。一般来说，在 C 语言内部函数代码出现错误时，会返回 <code>1</code> 或 <code>NULL</code>，并且同时会设置一个错误码 <code>errno</code>，以此来表示错误类型。</p>
<p>相比于其他高级语言对错误的抽象，C 语言的错误处理就显得比较“原始”了。</p>
<p>以下是 C 语言错误处理的典型示例程序：</p>
<figure class="highlight c"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;stdio.h&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;errno.h&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;string.h&gt;  // 包含 strerror 函数的头文件</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line">    <span class="comment">// 清除 errno 初始值，这是一个好的编程习惯</span></span><br><span class="line">    errno = <span class="number">0</span>;</span><br><span class="line"></span><br><span class="line">    FILE *file;</span><br><span class="line">    <span class="keyword">char</span> *filename = <span class="string">"example.txt"</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// 尝试以读取模式打开文件</span></span><br><span class="line">    file = fopen(filename, <span class="string">"r"</span>);</span><br><span class="line">    <span class="keyword">if</span> (file == <span class="literal">NULL</span>) &#123;</span><br><span class="line">        <span class="comment">// 打开文件出错</span></span><br><span class="line">        <span class="built_in">printf</span>(<span class="string">"Failed to open file: %s\n"</span>, filename);</span><br><span class="line">        <span class="comment">// 查看错误码 errno</span></span><br><span class="line">        <span class="built_in">printf</span>(<span class="string">"ErrNo: %d\n"</span>, errno);</span><br><span class="line">        <span class="comment">// perror 函数显示传入的字符串，后跟一个冒号、一个空格和当前 errno 值的文本表示形式</span></span><br><span class="line">        perror(<span class="string">"Error"</span>);</span><br><span class="line">        <span class="comment">// strerror 函数返回一个指针，指向当前 errno 值的文本表示形式</span></span><br><span class="line">        <span class="built_in">printf</span>(<span class="string">"Error: %s\n"</span>, strerror(errno));</span><br><span class="line">        <span class="comment">// 在发生错误时，大多数的 C 或 UNIX 函数调用返回 1 或 NULL</span></span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span>;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// 文件操作</span></span><br><span class="line">    <span class="built_in">printf</span>(<span class="string">"open file success\n"</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// process file...</span></span><br><span class="line"></span><br><span class="line">    <span class="comment">// 完成操作后，关闭文件</span></span><br><span class="line">    fclose(file);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> <span class="number">0</span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>我们尝试使用 <code>fopen</code> 来打开一个文件，<code>fopen</code> 函数返回值 <code>file</code> 可能是 <code>FILE*</code> 表示文件描述符，也可能是 <code>NULL</code> 表示函数出错。</p>
<p>所以我们需要通过 <code>if (file == NULL)</code> 来判断打开文件是否出错，如果出错，全局变量 <code>errno</code> 会被赋值，使用 <code>perror</code> 函数或者 <code>strerror(errno)</code> 可以读取错误码对应的错误描述信息。</p>
<blockquote>
<p>NOTE:<br><code>perror()</code> 函数打印传入的字符串，后跟一个冒号、一个空格和当前 <code>errno</code> 值的文本表示形式。<br><code>strerror()</code> 函数，返回一个指针，指针指向当前 <code>errno</code> 值的文本表示形式。</p>
</blockquote>
<blockquote>
<p>NOTE:<br>我们能在 <code>&lt;errno.h&gt;</code> 头文件中找到错误码定义：</p>
<figure class="highlight c"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">/*</span></span><br><span class="line"><span class="comment"> * Error codes</span></span><br><span class="line"><span class="comment"> */</span></span><br><span class="line"></span><br><span class="line"><span class="meta">#<span class="meta-keyword">define</span> EPERM           1               <span class="comment">/* Operation not permitted */</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">define</span> ENOENT          2               <span class="comment">/* No such file or directory */</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">define</span> ESRCH           3               <span class="comment">/* No such process */</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">define</span> EINTR           4               <span class="comment">/* Interrupted system call */</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">define</span> EIO             5               <span class="comment">/* Input/output error */</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">define</span> ENXIO           6               <span class="comment">/* Device not configured */</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">define</span> E2BIG           7               <span class="comment">/* Argument list too long */</span></span></span><br><span class="line">...</span><br></pre></td></tr></table></figure>
</blockquote>
<p>执行示例代码，打开一个不存在的文件，输出如下：</p>
<figure class="highlight bash"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">$ gcc main.c -g -o main</span><br><span class="line">$ ./main</span><br><span class="line">Failed to open file: example.txt</span><br><span class="line">ErrNo: 2</span><br><span class="line">Error: No such file or directory</span><br><span class="line">Error: No such file or directory</span><br></pre></td></tr></table></figure>

<p>这种错误处理方式存在一个很大的问题：<strong>返回值有二义性</strong>。</p>
<p><code>fopen</code> 函数即可能返回 <code>FILE*</code> 也可能返回 <code>NULL</code>，这是一种很糟糕的做法。</p>
<p>并且，很多人会因此忘记错误检查。</p>
<p>而在 C 语言中，之所以要这样处理错误，主要是因为 C 语言的函数只能有一个返回值。所以这也是一种没有办法的办法。</p>
<p>不过，这种方式并不能处理所有错误场景。</p>
<p>如果用 C 来实现 <code>div</code> 函数，就不能使用 <code>NULL</code> 作为返回值，<code>NULL</code> 无法转换成 <code>int</code> 类型。</p>
<p>我们只能这样做：</p>
<figure class="highlight c"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;stdio.h&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">div</span><span class="params">(<span class="keyword">int</span> a, <span class="keyword">int</span> b, <span class="keyword">int</span> *result)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">if</span> (b == <span class="number">0</span>) &#123;</span><br><span class="line">        <span class="keyword">return</span> <span class="number">-1</span>; <span class="comment">// 返回 -1 表示错误</span></span><br><span class="line">    &#125;</span><br><span class="line">    *result = a / b; <span class="comment">// 将结果存储在指针所指向的变量中</span></span><br><span class="line">    <span class="keyword">return</span> <span class="number">0</span>; <span class="comment">// 返回 0 表示成功</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line">    <span class="keyword">int</span> result;</span><br><span class="line">    <span class="keyword">int</span> err;</span><br><span class="line"></span><br><span class="line">    err = div(<span class="number">1</span>, <span class="number">0</span>, &amp;result);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// 错误处理</span></span><br><span class="line">    <span class="keyword">if</span> (err == <span class="number">-1</span>) &#123;</span><br><span class="line">        <span class="built_in">printf</span>(<span class="string">"division by zero\n"</span>);</span><br><span class="line">    &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">        <span class="built_in">printf</span>(<span class="string">"result: %d\n"</span>, result);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> <span class="number">0</span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><code>div</code> 函数还是单返回值，不过这个返回值只代表错误，返回 <code>0</code> 表示成功，返回 <code>-1</code> 表示失败。</p>
<p><code>div</code> 函数计算结果通过参数的形式，被存储在指针所指向的变量 <code>int *result</code> 中。</p>
<p>这也是 C 语言中错误处理的另一种典型做法。</p>
<p>但这种用参数接收计算结果的方式，我个人其实是不太喜欢的，因为我认为语义不够清晰。</p>
<blockquote>
<p>NOTE:<br>其实 C 函数支持返回结构体指针，这样虽然函数只能返回一个值，但可玩性就大大增加了，所以单返回值也不是不能接受。</p>
</blockquote>
<p>最后，我们再看一看 Go 语言中的错误处理。</p>
<h3 id="Go-错误处理"><a href="#Go-错误处理" class="headerlink" title="Go 错误处理"></a>Go 错误处理</h3><p>我在前文说 C 是“万物鼻祖”，这在编程世界里并不算太夸张的说法。Python 解释器就是用 C 语言写的，而 Go 语言作者之一 <a href="https://zh.wikipedia.org/wiki/肯·汤普逊" target="_blank" rel="noopener">肯·汤普逊</a> 同时又是 Unix 操作系统和 B 语言（C 语言的前身）作者，所以 Go 在设计之初，就大量参考了 C 语言的设计。</p>
<p>不难推测，Go 的错误处理也参考了 C 语言。事实也的确如此，Go 的错误处理继承自 C 语言，并在其基础上做了改进。</p>
<p>以下是 Go 语言错误处理的典型示例程序：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">package</span> main</span><br><span class="line"></span><br><span class="line"><span class="keyword">import</span> (</span><br><span class="line">	<span class="string">"errors"</span></span><br><span class="line">	<span class="string">"fmt"</span></span><br><span class="line">	<span class="string">"log"</span></span><br><span class="line">)</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">div</span><span class="params">(a, b <span class="keyword">int</span>)</span> <span class="params">(<span class="keyword">int</span>, error)</span></span> &#123;</span><br><span class="line">	<span class="keyword">if</span> b == <span class="number">0</span> &#123;</span><br><span class="line">		<span class="keyword">return</span> <span class="number">0</span>, errors.New(<span class="string">"division by zero"</span>)</span><br><span class="line">	&#125;</span><br><span class="line">	<span class="keyword">return</span> a / b, <span class="literal">nil</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">main</span><span class="params">()</span></span> &#123;</span><br><span class="line">	result, err := div(<span class="number">1</span>, <span class="number">0</span>)</span><br><span class="line">	<span class="keyword">if</span> err != <span class="literal">nil</span> &#123;</span><br><span class="line">		fmt.Println(err)</span><br><span class="line">		<span class="keyword">return</span></span><br><span class="line">	&#125;</span><br><span class="line">	fmt.Println(result)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>得益于 Go 函数支持多返回值，所以 Go 就不再需要 <code>errno</code> 了。</p>
<p>Go 定义了一个 <code>error</code> 类型，专门用来表示错误，使用 <code>errors.New</code> 可以轻松构建一个错误对象。</p>
<p>这也就引出了经典的 <code>if err != nil</code>，程序遇到错误就会走入此分支，我们需要在此做错误处理。</p>
<p>Go 中的 <code>error</code> 其实是一个接口：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">type</span> error <span class="keyword">interface</span> &#123;</span><br><span class="line">	Error() <span class="keyword">string</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>任何实现了 <code>error</code> 接口的类型，都可以是一个错误。</p>
<p>而我们通过 <code>errors.New</code> 创建的错误，其实就是一个内置错误类型的实现：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">New</span><span class="params">(text <span class="keyword">string</span>)</span> <span class="title">error</span></span> &#123;</span><br><span class="line">	<span class="keyword">return</span> &amp;errorString&#123;text&#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">type</span> errorString <span class="keyword">struct</span> &#123;</span><br><span class="line">	s <span class="keyword">string</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="params">(e *errorString)</span> <span class="title">Error</span><span class="params">()</span> <span class="title">string</span></span> &#123;</span><br><span class="line">	<span class="keyword">return</span> e.s</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>我们也完全可以根据自己的需要，自定义 <code>error</code>：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">type</span> MyError <span class="keyword">struct</span> &#123;</span><br><span class="line">	msg <span class="keyword">string</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="params">(e *MyError)</span> <span class="title">Error</span><span class="params">()</span> <span class="title">string</span></span> &#123;</span><br><span class="line">	<span class="keyword">return</span> e.msg</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>并且 <code>MyError</code> 中可以增加任何我们想要的字段和方法。</p>
<p>我们可以像这样处理不同类型的错误：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">if</span> err != <span class="literal">nil</span> &#123;</span><br><span class="line">	<span class="keyword">switch</span> err.(<span class="keyword">type</span>) &#123;</span><br><span class="line">	<span class="keyword">case</span> *MyError:</span><br><span class="line">		<span class="comment">// ...</span></span><br><span class="line">	<span class="keyword">case</span> *ZeroDivisionError:</span><br><span class="line">		<span class="comment">// ...</span></span><br><span class="line">	<span class="keyword">default</span>:</span><br><span class="line">		<span class="comment">// ...</span></span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>可以发现，Go 中的错误处理其实是对返回值的检查，并且我们可以通过类型断言 <code>err.(type)</code> 来判断 <code>error</code> 的具体类型。</p>
<p>有时候，我们想忽略错误，需要这样做：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">result, _ := div(<span class="number">1</span>, <span class="number">0</span>)</span><br></pre></td></tr></table></figure>

<p>在 Go 中必须使用 <code>_</code> 显式的忽略错误，否则如果不处理 <code>err</code> 程序会编译不通过。</p>
<p>因为 Go 函数可以返回多个值，所以这给我们处理错误带来了更大的灵活性，比如下面这个示例：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">type</span> SmsCode <span class="keyword">struct</span>&#123;&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="params">(c SmsCode)</span> <span class="title">Verify1</span><span class="params">()</span> <span class="params">(<span class="keyword">bool</span>, error)</span></span> &#123;</span><br><span class="line">	<span class="comment">// ...</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="params">(c SmsCode)</span> <span class="title">Verify2</span><span class="params">()</span> <span class="title">error</span></span> &#123;</span><br><span class="line">	<span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>假如我们有一个发送短信验证码的结构体 <code>SmsCode</code>，需要为其定义 <code>Verify</code> 方法来验证用户输入的短信验证码是否正确。</p>
<p>我们可以定义成 <code>Verify1</code> 这样，方法返回两个值，<code>bool</code> 值表示验证码是否正确，<code>error</code> 值表示代码执行过程中是否出错，比如 Redis 无法调通等。</p>
<p>我们也可以定义成 <code>Verify2</code> 这样，方法仅返回一个值，验证码错误也可以当作是一种 <code>error</code> 类型，比如 <code>errors.New(&quot;invalid sms code&quot;)</code>。</p>
<p>当然，这就是业务上需要我们自己做决策的地方了，和语言本身错误处理无关。这也正是因为 Go 提供的方便，让我们比在写 C 代码时可以更加灵活的处理错误。</p>
<p>不过，Go 中的错误处理也有弊端，看下面这个示例你就有体会了：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">a</span><span class="params">()</span> <span class="title">error</span></span> &#123;</span><br><span class="line">	<span class="comment">// ...</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">b</span><span class="params">()</span> <span class="title">error</span></span> &#123;</span><br><span class="line">	<span class="comment">// ...</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">c</span><span class="params">()</span> <span class="title">error</span></span> &#123;</span><br><span class="line">	<span class="comment">// ...</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">main</span><span class="params">()</span></span> &#123;</span><br><span class="line">	err := a()</span><br><span class="line">	<span class="keyword">if</span> err != <span class="literal">nil</span> &#123;</span><br><span class="line">		log.Fatal(err)</span><br><span class="line">	&#125;</span><br><span class="line">	err = b()</span><br><span class="line">	<span class="keyword">if</span> err != <span class="literal">nil</span> &#123;</span><br><span class="line">		log.Fatal(err)</span><br><span class="line">	&#125;</span><br><span class="line">	err = c()</span><br><span class="line">	<span class="keyword">if</span> err != <span class="literal">nil</span> &#123;</span><br><span class="line">		log.Fatal(err)</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>是不是有点抓狂。</p>
<p>哈哈，其实只要我们做好封装，还是可以避免这种代码产生的。</p>
<p>相较于 Python，Go 对错误处理更加谨慎，我们不能通过在代码块最外层写一个 <code>try...except...</code> 来进行兜底，只能一步一步去处理错误。</p>
<p>此外，Python 在异常处理中提供了 <code>finally</code> 语句可以方便我们释放资源，不论代码是否执行出错，<code>finally</code> 语句最终都会执行。</p>
<p>Go 也提供了类似功能，即 <code>defer</code> 语句：</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">main</span><span class="params">()</span></span> &#123;</span><br><span class="line">	<span class="keyword">defer</span> <span class="function"><span class="keyword">func</span><span class="params">()</span></span> &#123;</span><br><span class="line">		fmt.Println(<span class="string">"release resources"</span>)</span><br><span class="line">	&#125;()</span><br><span class="line"></span><br><span class="line">	result, err := div(<span class="number">1</span>, <span class="number">0</span>)</span><br><span class="line">	<span class="keyword">if</span> err != <span class="literal">nil</span> &#123;</span><br><span class="line">		fmt.Println(err)</span><br><span class="line">		<span class="keyword">return</span></span><br><span class="line">	&#125;</span><br><span class="line">	fmt.Println(result)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>执行示例代码：</p>
<figure class="highlight bash"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">$ go run main.go</span><br><span class="line">division by zero</span><br><span class="line">release resources</span><br></pre></td></tr></table></figure>

<p>被 <code>defer</code> 修饰的函数会在外层的 <code>main</code> 函数退出前被调用执行。</p>
<blockquote>
<p>NOTE:<br>C 语言可以使用 <a href="https://coolshell.cn/articles/11112.html" target="_blank" rel="noopener"><code>goto fail;</code></a> 跳转到指定代码块来进行资源释放。</p>
</blockquote>
<p>另外，Go 与其他主流编程语言在错误处理上有一个很大的分歧，Go 区分了「错误」和「异常」。</p>
<figure class="highlight go"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">package</span> main</span><br><span class="line"></span><br><span class="line"><span class="keyword">import</span> <span class="string">"fmt"</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">mayPanic</span><span class="params">()</span></span> &#123;</span><br><span class="line">	<span class="built_in">panic</span>(<span class="string">"a problem"</span>)</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">func</span> <span class="title">main</span><span class="params">()</span></span> &#123;</span><br><span class="line">	<span class="keyword">defer</span> <span class="function"><span class="keyword">func</span><span class="params">()</span></span> &#123;</span><br><span class="line">		<span class="keyword">if</span> r := <span class="built_in">recover</span>(); r != <span class="literal">nil</span> &#123;</span><br><span class="line">			fmt.Println(<span class="string">"recovered error:"</span>, r)</span><br><span class="line">		&#125; <span class="keyword">else</span> &#123;</span><br><span class="line">			fmt.Println(<span class="string">"recovered success"</span>)</span><br><span class="line">		&#125;</span><br><span class="line">	&#125;()</span><br><span class="line"></span><br><span class="line">	mayPanic()</span><br><span class="line"></span><br><span class="line">	fmt.Println(<span class="string">"after mayPanic()"</span>)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>在 Go 中 <code>panic</code> 表示一个异常，与 <code>error</code> 错误不同，默认情况下，遇到 <code>panic</code> 调用，Go 程序会崩溃并退出。</p>
<p>可以使用 <code>recover</code> 来捕获 <code>panic</code> 抛出的异常，但是要注意 <code>recover</code> 一定要放在函数入口处的 <code>defer</code> 语句中，因为只有这样才能保证 <code>recover</code> 会被调用。</p>
<p>我们可以在主动捕获异常的地方，自行处理出现异常后的逻辑。</p>
<p>执行示例代码：</p>
<figure class="highlight bash"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">$ go run main.go</span><br><span class="line">recovered error: a problem</span><br></pre></td></tr></table></figure>

<p>可以发现 <code>after mayPanic()</code> 并没有被打印。这说明代码执行到 <code>panic</code> 以后就中断了，<code>panic</code> 会抛出异常，然后异常被 <code>recover</code> 捕获并处理。</p>
<p><code>recover</code> 可以看作是一种全局的兜底异常处理方案，Gin 框架就通过中间件的方式，在处理请求的时候 <code>recover</code> 住未知的异常，以防程序退出。</p>
<p>不过绝大多数情况下并不建议使用 <code>panic</code> + <code>recover</code> 机制，<code>panic</code> 表示意外的异常，而我们在编写代码阶段，更多需要处理的情况是可以预见的错误 <code>error</code>。</p>
<p>对于真正意外的情况，比如数组索引越界，我们才会使用 <code>panic</code>，对于一般性错误，我们应该是使用 <code>error</code> 来进行处理。</p>
<p>以上便是 Go 语言的错误处理机制。</p>
<h3 id="总结"><a href="#总结" class="headerlink" title="总结"></a>总结</h3><p>Python 的错误处理方式在主流编程语言中最为常见，只不过其他编程语言的关键字一般为 <code>try...catch...finally</code>。</p>
<p>这种异常处理方式的好处是代码简洁优雅，所以是最被程序员所接受的一种错误处理方式。</p>
<p>不知道你有没有注意，我在 Python 异常处理的示例代码中，还写了一个 <code>else</code> 分支，其实 Python 异常处理完整逻辑是 <code>try...except...else...finally</code>，<code>else</code> 分支的功能你可以自己思考下是干什么用的。</p>
<p>C 的错误处理比较“原始”，很大原因是 C 函数只能返回单个值。所以就可能出现一个返回值，存在多种用途的现象。不过既然都用 C 语言开发程序了，这一点显然是要程序员自己要解决的问题。</p>
<p>Go 因为是后起之秀，所以可以参考它的前辈们，来设计属于自己风格的错误处理机制。不过即使这样，Go 的错误处理仍然是被吐槽最多的。</p>
<p>我倒是觉得这种错误处理非常的 “Go”，很有 Go 语言的特点，大道至简。</p>
<p>Go 在 <a href="https://go.dev/doc/faq#exceptions" target="_blank" rel="noopener">FAQ</a> 中解释了为什么 Go 中没有“异常”，感兴趣的读者可以跳转过去查看。</p>
<p>对比了三种主流编程语言的错误处理以后，你是否对 Go 语言的错误处理有了更新的认识？你喜欢哪种错误处理方式？可以在评论区进行交流。</p>
<p>本文示例源码我都放在了 <a href="https://github.com/jianghushinian/blog-go-example/tree/main/error/error-exception-errno" target="_blank" rel="noopener">GitHub</a> 中，欢迎点击查看。</p>
<p>希望此文能对你有所启发。</p>
<p><strong>延伸阅读</strong></p>
<ul>
<li>The Python Tutorial：Errors and Exceptions：<a href="https://docs.python.org/3/tutorial/errors.html" target="_blank" rel="noopener">https://docs.python.org/3/tutorial/errors.html</a></li>
<li>C 错误处理：<a href="https://www.runoob.com/cprogramming/c-error-handling.html" target="_blank" rel="noopener">https://www.runoob.com/cprogramming/c-error-handling.html</a></li>
<li>Go 编程模式：错误处理：<a href="https://coolshell.cn/articles/21140.html" target="_blank" rel="noopener">https://coolshell.cn/articles/21140.html</a></li>
<li>Why does Go not have exceptions?：<a href="https://go.dev/doc/faq#exceptions" target="_blank" rel="noopener">https://go.dev/doc/faq#exceptions</a></li>
<li>Why Go gets exceptions right：<a href="https://dave.cheney.net/2012/01/18/why-go-gets-exceptions-right" target="_blank" rel="noopener">https://dave.cheney.net/2012/01/18/why-go-gets-exceptions-right</a></li>
<li>The Go Blog：Defer, Panic, and Recover：<a href="https://go.dev/blog/defer-panic-and-recover" target="_blank" rel="noopener">https://go.dev/blog/defer-panic-and-recover</a></li>
<li>本文 GitHub 示例代码：<a href="https://github.com/jianghushinian/blog-go-example/tree/main/error/error-exception-errno" target="_blank" rel="noopener">https://github.com/jianghushinian/blog-go-example/tree/main/error/error-exception-errno</a></li>
</ul>
<p><strong>联系我</strong></p>
<ul>
<li>公众号：<a href="https://jianghushinian.cn/about" target="_blank" rel="noopener">Go编程世界</a></li>
<li>微信：jianghushinian</li>
<li>邮箱：<a href="mailto:jianghushinian007@outlook.com">jianghushinian007@outlook.com</a></li>
<li>博客：<a href="https://jianghushinian.cn" target="_blank" rel="noopener">https://jianghushinian.cn</a></li>
</ul>

        </div>

        <blockquote class="post-copyright">
    
    <div class="content">
        
<span class="post-time">
    最后更新时间：<time datetime="2025-09-11T06:46:31.629Z" itemprop="dateUpdated">2025-09-11 14:46:31</time>
</span><br>


        
        <a href="/2024/09/06/go-error-guidelines-error-exception-errno/" target="_blank" rel="external">http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/</a>
        
    </div>
    
    <footer>
        <a href="http://www.jianghushinian.cn">
            <img src="/img/avatar.png" alt="江湖十年">
            江湖十年
        </a>
    </footer>
</blockquote>

        


        <div class="post-footer">
            
	<ul class="article-tag-list" itemprop="keywords"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/Error/" rel="tag">Error</a></li><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/Go/" rel="tag">Go</a></li></ul>


            
<div class="page-share-wrap">
    

<div class="page-share" id="pageShare">
    <ul class="reset share-icons">
      <li>
        <a class="weibo share-sns" target="_blank" href="http://service.weibo.com/share/share.php?url=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/&title=《Go 错误处理指北：Error vs Exception vs ErrNo》 — 江湖十年&pic=http://www.jianghushinian.cn/img/avatar.png" data-title="微博">
          <i class="icon icon-weibo"></i>
        </a>
      </li>
      <li>
        <a class="weixin share-sns wxFab" href="javascript:;" data-title="微信">
          <i class="icon icon-weixin"></i>
        </a>
      </li>
      <li>
        <a class="qq share-sns" target="_blank" href="http://connect.qq.com/widget/shareqq/index.html?url=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/&title=《Go 错误处理指北：Error vs Exception vs ErrNo》 — 江湖十年&source=很多有其他编程语言经验的人初次接触 Go 语言时，想必对 if err != nil 的错误处理方式感到新奇，之后用久了，竟发现有点令人抓狂。
因为很多人..." data-title=" QQ">
          <i class="icon icon-qq"></i>
        </a>
      </li>
      <li>
        <a class="facebook share-sns" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/" data-title=" Facebook">
          <i class="icon icon-facebook"></i>
        </a>
      </li>
      <li>
        <a class="twitter share-sns" target="_blank" href="https://twitter.com/intent/tweet?text=《Go 错误处理指北：Error vs Exception vs ErrNo》 — 江湖十年&url=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/&via=http://www.jianghushinian.cn" data-title=" Twitter">
          <i class="icon icon-twitter"></i>
        </a>
      </li>
      <li>
        <a class="google share-sns" target="_blank" href="https://plus.google.com/share?url=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/" data-title=" Google+">
          <i class="icon icon-google-plus"></i>
        </a>
      </li>
    </ul>
 </div>



    <a href="javascript:;" id="shareFab" class="page-share-fab waves-effect waves-circle">
        <i class="icon icon-share-alt icon-lg"></i>
    </a>
</div>



        </div>
    </div>

    
<nav class="post-nav flex-row flex-justify-between">
  
    <div class="waves-block waves-effect prev">
      <a href="/2024/09/14/go-error-guidelines-pkg-errors/" id="post-prev" class="post-nav-link">
        <div class="tips"><i class="icon icon-angle-left icon-lg icon-pr"></i> Prev</div>
        <h4 class="title">Go 错误处理指北：pkg/errors 源码解读</h4>
      </a>
    </div>
  

  
    <div class="waves-block waves-effect next">
      <a href="/2024/08/26/go-design-patterns-builder/" id="post-next" class="post-nav-link">
        <div class="tips">Next <i class="icon icon-angle-right icon-lg icon-pl"></i></div>
        <h4 class="title">Builder 模式在 Go 语言中的应用</h4>
      </a>
    </div>
  
</nav>



    


    <script src="/js/md5.min.js"></script>
    <section class="comments" id="comments">
        <div id="disqus_thread"></div>
        <script type="text/javascript">
            var disqus_shortname = 'https-jianghushinian-cn';
            var disqus_identifier = location.pathname.slice(1,);
            var disqus_url = 'https://jianghushinian.cn/' + disqus_identifier;
            (function () {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the comments.</noscript>
    </section>


















</article>



</div>

        <footer class="footer">
    <div class="top">
        
<p>
    <span id="busuanzi_container_site_uv" style='display:none'>
        <span id="busuanzi_value_site_uv"></span>
    </span>
    <span id="busuanzi_container_site_pv" style='display:none'>
        <span id="busuanzi_value_site_pv"></span>
    </span>
</p>


        <p>
            
                <span><a href="/atom.xml" target="_blank" class="rss" title="rss"><i class="icon icon-lg icon-rss"></i></a></span>
            
            <span>博客内容遵循 <a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">知识共享 署名 - 非商业性 - 相同方式共享 4.0 国际协议</a></span>
        </p>
    </div>
    <div class="bottom">
        <p><span>江湖十年 &copy; 2019 - 2025</span>
            <span>
                
                Power by <a href="http://hexo.io/" target="_blank">Hexo</a> Theme <a href="https://github.com/yscoder/hexo-theme-indigo" target="_blank">indigo</a>
            </span>
        </p>
    </div>
</footer>

    </main>
    <div class="mask" id="mask"></div>
<a href="javascript:;" id="gotop" class="waves-effect waves-circle waves-light"><span class="icon icon-lg icon-chevron-up"></span></a>



<div class="global-share" id="globalShare">
    <ul class="reset share-icons">
      <li>
        <a class="weibo share-sns" target="_blank" href="http://service.weibo.com/share/share.php?url=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/&title=《Go 错误处理指北：Error vs Exception vs ErrNo》 — 江湖十年&pic=http://www.jianghushinian.cn/img/avatar.png" data-title="微博">
          <i class="icon icon-weibo"></i>
        </a>
      </li>
      <li>
        <a class="weixin share-sns wxFab" href="javascript:;" data-title="微信">
          <i class="icon icon-weixin"></i>
        </a>
      </li>
      <li>
        <a class="qq share-sns" target="_blank" href="http://connect.qq.com/widget/shareqq/index.html?url=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/&title=《Go 错误处理指北：Error vs Exception vs ErrNo》 — 江湖十年&source=很多有其他编程语言经验的人初次接触 Go 语言时，想必对 if err != nil 的错误处理方式感到新奇，之后用久了，竟发现有点令人抓狂。
因为很多人..." data-title=" QQ">
          <i class="icon icon-qq"></i>
        </a>
      </li>
      <li>
        <a class="facebook share-sns" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/" data-title=" Facebook">
          <i class="icon icon-facebook"></i>
        </a>
      </li>
      <li>
        <a class="twitter share-sns" target="_blank" href="https://twitter.com/intent/tweet?text=《Go 错误处理指北：Error vs Exception vs ErrNo》 — 江湖十年&url=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/&via=http://www.jianghushinian.cn" data-title=" Twitter">
          <i class="icon icon-twitter"></i>
        </a>
      </li>
      <li>
        <a class="google share-sns" target="_blank" href="https://plus.google.com/share?url=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/" data-title=" Google+">
          <i class="icon icon-google-plus"></i>
        </a>
      </li>
    </ul>
 </div>


<div class="page-modal wx-share" id="wxShare">
    <a class="close" href="javascript:;"><i class="icon icon-close"></i></a>
    <p>扫一扫，分享到微信</p>
    <img src="//api.qrserver.com/v1/create-qr-code/?data=http://www.jianghushinian.cn/2024/09/06/go-error-guidelines-error-exception-errno/" alt="微信分享二维码">
</div>




    <script src="//cdn.bootcss.com/node-waves/0.7.4/waves.min.js"></script>
<script>
var BLOG = { ROOT: '/', SHARE: true, REWARD: false };


</script>

<script src="//unpkg.com/hexo-theme-material-indigo@latest/js/main.min.js"></script>


<div class="search-panel" id="search-panel">
    <ul class="search-result" id="search-result"></ul>
</div>
<template id="search-tpl">
<li class="item">
    <a href="{path}" class="waves-block waves-effect">
        <div class="title ellipsis" title="{title}">{title}</div>
        <div class="flex-row flex-middle">
            <div class="tags ellipsis">
                {tags}
            </div>
            <time class="flex-col time">{date}</time>
        </div>
    </a>
</li>
</template>

<script src="//unpkg.com/hexo-theme-material-indigo@latest/js/search.min.js" async></script>






<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>





</body>
</html>
