<!DOCTYPE html>
<html>
<head>
    

    

    



    <meta charset="utf-8">
    
    
    
    
    <title>Python 异常处理机制 | 江湖十年 | 学而不思则罔，思而不学则殆。</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <meta name="theme-color" content="#3F51B5">
    
    
    <meta name="keywords" content="Python">
    <meta name="description" content="Python 解释器在执行代码时，如果发生错误，解释器会立即抛出异常并终止程序的运行。异常处理，实际上就是一种错误处理机制。">
<meta property="og:type" content="article">
<meta property="og:title" content="Python 异常处理机制">
<meta property="og:url" content="http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/index.html">
<meta property="og:site_name" content="江湖十年">
<meta property="og:description" content="Python 解释器在执行代码时，如果发生错误，解释器会立即抛出异常并终止程序的运行。异常处理，实际上就是一种错误处理机制。">
<meta property="og:locale" content="zh_CN">
<meta property="article:published_time" content="2019-09-16T12:07:24.000Z">
<meta property="article:modified_time" content="2022-12-24T13:16:45.345Z">
<meta property="article:author" content="江湖十年">
<meta property="article:tag" content="Python">
<meta name="twitter:card" content="summary">
    
        <link rel="alternate" type="application/atom+xml" title="江湖十年" href="/atom.xml">
    
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="stylesheet" href="//unpkg.com/hexo-theme-material-indigo@latest/css/style.css">
    <script>window.lazyScripts=[]</script>

    <!-- custom head -->
    

<meta name="generator" content="Hexo 4.2.0"></head>

<body>
    <div id="loading" class="active"></div>

    <aside id="menu" class="hide" >
  <div class="inner flex-row-vertical">
    <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="menu-off">
        <i class="icon icon-lg icon-close"></i>
    </a>
    <div class="brand-wrap" style="background-image:url(/img/brand.jpg)">
      <div class="brand">
        <a href="/" class="avatar waves-effect waves-circle waves-light">
          <img src="/img/avatar.png">
        </a>
        <hgroup class="introduce">
          <h5 class="nickname">江湖十年</h5>
          <a href="mailto:jianghushinian007@outlook.com" title="jianghushinian007@outlook.com" class="mail">jianghushinian007@outlook.com</a>
        </hgroup>
      </div>
    </div>
    <div class="scroll-wrap flex-col">
      <ul class="nav">
        
            <li class="waves-block waves-effect">
              <a href="/"  >
                <i class="icon icon-lg icon-home"></i>
                主页
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/archives"  >
                <i class="icon icon-lg icon-archives"></i>
                归档
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/tags"  >
                <i class="icon icon-lg icon-tags"></i>
                标签
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/categories"  >
                <i class="icon icon-lg icon-th-list"></i>
                分类
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/about"  >
                <i class="icon icon-lg icon-link"></i>
                关于
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="https://github.com/jianghushinian" target="_blank" >
                <i class="icon icon-lg icon-github"></i>
                Github
              </a>
            </li>
        
      </ul>
    </div>
  </div>
</aside>

    <main id="main">
        <header class="top-header" id="header">
    <div class="flex-row">
        <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light on" id="menu-toggle">
          <i class="icon icon-lg icon-navicon"></i>
        </a>
        <div class="flex-col header-title ellipsis">Python 异常处理机制</div>
        
        <div class="search-wrap" id="search-wrap">
            <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="back">
                <i class="icon icon-lg icon-chevron-left"></i>
            </a>
            <input type="text" id="key" class="search-input" autocomplete="off" placeholder="输入感兴趣的关键字">
            <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="search">
                <i class="icon icon-lg icon-search"></i>
            </a>
        </div>
        
        
        <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="menuShare">
            <i class="icon icon-lg icon-share-alt"></i>
        </a>
        
    </div>
</header>
<header class="content-header post-header">

    <div class="container fade-scale">
        <h1 class="title">Python 异常处理机制</h1>
        <h5 class="subtitle">
            
                <time datetime="2019-09-16T12:07:24.000Z" itemprop="datePublished" class="page-time">
  2019-09-16
</time>


	<ul class="article-category-list"><li class="article-category-list-item"><a class="article-category-list-link" href="/categories/Python/">Python</a></li></ul>

            
        </h5>
    </div>

    


</header>


<div class="container body-wrap">
    
    <aside class="post-widget">
        <nav class="post-toc-wrap post-toc-shrink" id="post-toc">
            <h4>TOC</h4>
            <ol class="post-toc"><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#异常的常见场景"><span class="post-toc-number">1.</span> <span class="post-toc-text">异常的常见场景</span></a></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#Python-异常类及继承关系"><span class="post-toc-number">2.</span> <span class="post-toc-text">Python 异常类及继承关系</span></a></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#处理异常"><span class="post-toc-number">3.</span> <span class="post-toc-text">处理异常</span></a></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#自定义异常"><span class="post-toc-number">4.</span> <span class="post-toc-text">自定义异常</span></a></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#异常处理时可能会遇到的问题"><span class="post-toc-number">5.</span> <span class="post-toc-text">异常处理时可能会遇到的问题</span></a></li></ol>
        </nav>
    </aside>


<article id="post-Python-异常处理机制"
  class="post-article article-type-post fade" itemprop="blogPost">

    <div class="post-card">
        <h1 class="post-card-title">Python 异常处理机制</h1>
        <div class="post-meta">
            <time class="post-time" title="2019-09-16 20:07:24" datetime="2019-09-16T12:07:24.000Z"  itemprop="datePublished">2019-09-16</time>

            
	<ul class="article-category-list"><li class="article-category-list-item"><a class="article-category-list-link" href="/categories/Python/">Python</a></li></ul>



            
<span id="busuanzi_container_page_pv" title="文章总阅读量" style='display:none'>
    <i class="icon icon-eye icon-pr"></i><span id="busuanzi_value_page_pv"></span>
</span>


        </div>
        <div class="post-content" id="post-content" itemprop="postContent">
            <p>Python 解释器在执行代码时，如果发生错误，解释器会立即抛出异常并终止程序的运行。异常处理，实际上就是一种错误处理机制。</p>
<a id="more"></a>

<h3 id="异常的常见场景"><a href="#异常的常见场景" class="headerlink" title="异常的常见场景"></a>异常的常见场景</h3><p>程序产生异常的原因有很多种，举例来说，在 Python 中做除法运算时，<code>0</code> 是不能做除数的，否则将会抛出 <code>ZeroDivisionError</code> 异常。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&gt;&gt;&gt; </span><span class="number">1</span> / <span class="number">0</span></span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"&lt;stdin&gt;"</span>, line <span class="number">1</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">ZeroDivisionError: division by zero</span><br></pre></td></tr></table></figure>

<p>在 Python 控制台输入 <code>1 / 0</code> 并回车执行，解释器将立即抛出 <code>ZeroDivisionError</code> 异常，由异常提示信息<code>division by zero</code> 可知，产生异常的原因是 <code>0</code> 作为了除数。</p>
<p>还有很多其他容易产生异常的场景，如在发送网络请求时，有可能会遇到连接错误、超时等；访问系统资源时，有可能会遇到权限不足、资源不存在等。</p>
<p>在 Python 中，每一种异常都用一个类来定义，上面的 <code>ZeroDivisionError</code> 实际上就是一个异常类。Python 内置了很多种异常类，接下来就介绍下 Python 中的异常类。</p>
<h3 id="Python-异常类及继承关系"><a href="#Python-异常类及继承关系" class="headerlink" title="Python 异常类及继承关系"></a>Python 异常类及继承关系</h3><p>Python 提供了一个基础异常类 <code>BaseException</code>，所有其他的异常都继承于此类。以下列出了所有内置异常类及继承关系。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br></pre></td><td class="code"><pre><span class="line">BaseException</span><br><span class="line"> +-- SystemExit</span><br><span class="line"> +-- KeyboardInterrupt</span><br><span class="line"> +-- GeneratorExit</span><br><span class="line"> +-- Exception</span><br><span class="line">      +-- StopIteration</span><br><span class="line">      +-- StopAsyncIteration</span><br><span class="line">      +-- ArithmeticError</span><br><span class="line">      |    +-- FloatingPointError</span><br><span class="line">      |    +-- OverflowError</span><br><span class="line">      |    +-- ZeroDivisionError</span><br><span class="line">      +-- AssertionError</span><br><span class="line">      +-- AttributeError</span><br><span class="line">      +-- BufferError</span><br><span class="line">      +-- EOFError</span><br><span class="line">      +-- ImportError</span><br><span class="line">      |    +-- ModuleNotFoundError</span><br><span class="line">      +-- LookupError</span><br><span class="line">      |    +-- IndexError</span><br><span class="line">      |    +-- KeyError</span><br><span class="line">      +-- MemoryError</span><br><span class="line">      +-- NameError</span><br><span class="line">      |    +-- UnboundLocalError</span><br><span class="line">      +-- OSError</span><br><span class="line">      |    +-- BlockingIOError</span><br><span class="line">      |    +-- ChildProcessError</span><br><span class="line">      |    +-- ConnectionError</span><br><span class="line">      |    |    +-- BrokenPipeError</span><br><span class="line">      |    |    +-- ConnectionAbortedError</span><br><span class="line">      |    |    +-- ConnectionRefusedError</span><br><span class="line">      |    |    +-- ConnectionResetError</span><br><span class="line">      |    +-- FileExistsError</span><br><span class="line">      |    +-- FileNotFoundError</span><br><span class="line">      |    +-- InterruptedError</span><br><span class="line">      |    +-- IsADirectoryError</span><br><span class="line">      |    +-- NotADirectoryError</span><br><span class="line">      |    +-- PermissionError</span><br><span class="line">      |    +-- ProcessLookupError</span><br><span class="line">      |    +-- TimeoutError</span><br><span class="line">      +-- ReferenceError</span><br><span class="line">      +-- RuntimeError</span><br><span class="line">      |    +-- NotImplementedError</span><br><span class="line">      |    +-- RecursionError</span><br><span class="line">      +-- SyntaxError</span><br><span class="line">      |    +-- IndentationError</span><br><span class="line">      |         +-- TabError</span><br><span class="line">      +-- SystemError</span><br><span class="line">      +-- TypeError</span><br><span class="line">      +-- ValueError</span><br><span class="line">      |    +-- UnicodeError</span><br><span class="line">      |         +-- UnicodeDecodeError</span><br><span class="line">      |         +-- UnicodeEncodeError</span><br><span class="line">      |         +-- UnicodeTranslateError</span><br><span class="line">      +-- Warning</span><br><span class="line">           +-- DeprecationWarning</span><br><span class="line">           +-- PendingDeprecationWarning</span><br><span class="line">           +-- RuntimeWarning</span><br><span class="line">           +-- SyntaxWarning</span><br><span class="line">           +-- UserWarning</span><br><span class="line">           +-- FutureWarning</span><br><span class="line">           +-- ImportWarning</span><br><span class="line">           +-- UnicodeWarning</span><br><span class="line">           +-- BytesWarning</span><br><span class="line">           +-- ResourceWarning</span><br></pre></td></tr></table></figure>

<p>乍一看，几十种异常类感觉有点头大，其实大可不必担心。这么多异常我们可以概括的将其分为两大类，系统类异常和非系统类异常。系统类异常包括 <code>SystemExit</code>、<code>KeyboardInterrupt</code>、<code>GeneratorExit</code>，非系统类异常就是 <code>Exception</code> 及其所有子类。可以看到，只有这 4 个异常类是直接继承自异常基类 <code>BaseException</code>，所有其他异常类都继承自 <code>Exception</code>。</p>
<p>实际上，我们真正在编码过程中，常见的异常类并不多，如读取文件时可能抛出的 <code>FileNotFoundError</code> 异常表示文件未找到，根据下标获取列表元素时可能抛出的 <code>IndexError</code> 异常表示索引越界，以及上面示例介绍的除 0 异常 <code>ZeroDivisionError</code> 等。你并不需要把这么多种异常都背下来，你只需在遇到异常时查看文档即可。而比较常见的异常类，遇到过几次你就会了然于心了，下次写代码的时候你就能够预判哪些地方可能会出现什么样异常。</p>
<h3 id="处理异常"><a href="#处理异常" class="headerlink" title="处理异常"></a>处理异常</h3><p>上面介绍了 Python 中异常的继承关系，以及一些常见的异常场景。接下来我们就要学习如何处理异常，因为程序一旦产生异常，如果不进行处理，程序就会自动终止运行。做好异常处理才能够使程序在遇到异常的时候不至于终止而继续运行下去。</p>
<p>一个比较完整的异常处理代码示例如下：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    ...  <span class="comment"># 可能产生异常的代码</span></span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    ...  <span class="comment"># 异常处理代码</span></span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    ...  <span class="comment"># 没有产生异常时执行的代码</span></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    ...  <span class="comment"># 不管是否产生异常，都会执行的代码</span></span><br></pre></td></tr></table></figure>

<p>其中，<code>try</code> 语句块内编写的是一些有可能产生异常的代码块，一旦产生异常，就会被 <code>except</code> 关键字所捕获，<code>except</code> 关键字后面跟着的是要捕获的异常类型，<code>Exception</code> 代表捕获所有非系统类异常，<code>as e</code> 是给捕获的异常起一个别名 <code>e</code>，这个别名可以是任意符合 Python 变量命名规范的标识符，有了这个别名，就可以在 <code>except</code> 代码块中使用这个别名了，而如果 <code>try</code> 代码块中执行的代码没有产生异常，程序就会跳过<code>except</code> 代码块直接执行 <code>else</code> 代码块中的逻辑，无论是否产生异常 <code>finally</code> 代码块中的代码最终一定会被执行。</p>
<p>我们还是拿前面 <code>1 / 0</code> 的示例来通过实际代码观察下异常代码执行逻辑：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    print(<span class="string">'try 代码块开始执行'</span>)</span><br><span class="line">    <span class="number">1</span> / <span class="number">0</span>  <span class="comment"># 会产生异常的代码</span></span><br><span class="line">    print(<span class="string">'try 代码块执行完毕'</span>)</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'打印异常信息:'</span>, e)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    print(<span class="string">'没有产生异常'</span>)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'finally'</span>)</span><br></pre></td></tr></table></figure>

<p>代码执行结果如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">try 代码块开始执行</span><br><span class="line">打印异常信息: division by zero</span><br><span class="line">finally</span><br></pre></td></tr></table></figure>

<p>可以看到，由于 <code>1 / 0</code> 会产生异常，所以 <code>print(&#39;try 代码块执行完毕&#39;)</code> 这句代码并没有执行，产生异常后直接执行了 <code>except</code> 代码块中的代码。由于 <code>else</code> 代码块只有在不产生异常的情况下才会被执行，所以 <code>else</code> 语句块中的代码也没有执行，而 <code>finally</code> 语句块中的代码最终被执行了。</p>
<p>我们再来对比下不产生异常时代码的执行逻辑：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    print(<span class="string">'try 代码块开始执行'</span>)</span><br><span class="line">    <span class="number">1</span> / <span class="number">1</span>  <span class="comment"># 不会产生异常</span></span><br><span class="line">    print(<span class="string">'try 代码块执行完毕'</span>)</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'打印异常信息:'</span>, e)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    print(<span class="string">'没有产生异常'</span>)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'finally'</span>)</span><br></pre></td></tr></table></figure>

<p>代码执行结果如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">try 代码块开始执行</span><br><span class="line">try 代码块执行完毕</span><br><span class="line">没有产生异常</span><br><span class="line">finally</span><br></pre></td></tr></table></figure>

<p>两段代码做一下对比，就很容易看出异常处理的执行逻辑了。</p>
<p>事实上，上面异常处理的代码示例中 <code>else</code> 和 <code>finally</code> 是可以被省略的。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    print(<span class="string">'try 代码块开始执行'</span>)</span><br><span class="line">    <span class="number">1</span> / <span class="number">0</span></span><br><span class="line">    print(<span class="string">'try 代码块执行完毕'</span>)</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'打印异常信息:'</span>, e)</span><br></pre></td></tr></table></figure>

<p>这种写法也是我们编码过程中用的最多的写法。</p>
<p>上面说到 <code>except</code> 关键字能够捕获到异常，但其实是否执行 <code>except</code> 代码块是由跟在后面的 <code>Exception</code> 异常类决定的。<code>Exception</code> 能够捕获其所有子类及自身的异常，以上代码之所以能够捕获异常，是因为 <code>1 / 0</code> 产生的 <code>ZeroDivisionError</code> 类实际上是 <code>Exception</code> 类的子类。这里我们明确知道会产生 <code>ZeroDivisionError</code> 异常，所以更通常的写法是将 <code>except Exception as e:</code> 这句代码换成 <code>except ZeroDivisionError as e:</code>。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    print(<span class="string">'try 代码块开始执行'</span>)</span><br><span class="line">    <span class="number">1</span> / <span class="number">0</span></span><br><span class="line">    print(<span class="string">'try 代码块执行完毕'</span>)</span><br><span class="line"><span class="keyword">except</span> ZeroDivisionError <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'打印异常信息:'</span>, e)</span><br></pre></td></tr></table></figure>

<p>有时候一段代码有可能产生多种异常，如 <code>Web</code> 开发中的登录接口，往往需要前端通过 <code>AJAX</code> 将用户输入的 <code>username</code>（用户名）、<code>password</code>（密码）等信息组成 <code>JSON</code> 数据传递到后台，后台可能会先将 <code>JSON</code> 数据解析成字典，然后通过字典的 <code>key</code> 也就是 <code>username</code> 和 <code>password</code> 来获取用户输入的数据，最终完成登录操作。在这个过程中，解析 <code>JSON</code> 有可能产生异常，从解析后的字典中获取数据也有可能因为 <code>key</code> 不存在而产生异常。这个时候就需要 <code>except</code> 能够同时捕获多种异常，示例代码如下：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> json</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    data = request.body</span><br><span class="line">    json_data = json.loads(data)  <span class="comment"># 解析 JSON 有可能抛出 json.JSONDecodeError 异常</span></span><br><span class="line">    username = json_data[<span class="string">'username'</span>]  <span class="comment"># 如果 key 不存在则抛出 KeyError 异常</span></span><br><span class="line">    password = json_data[<span class="string">'password'</span>]</span><br><span class="line">    ...</span><br><span class="line"><span class="keyword">except</span> (json.JSONDecodeError, KeyError) <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'打印异常信息:'</span>, e)</span><br></pre></td></tr></table></figure>

<p>如果想用 <code>except</code> 同时能够捕获多种异常，可以将多个异常类组成一个元组跟在 <code>except</code> 后面。这样只要抛出的异常在元组内，<code>except</code> 代码块中的代码就会被执行。</p>
<p>其实捕获多种异常还有另一种写法：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> json</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    data = <span class="string">'&#123;&#125;'</span></span><br><span class="line">    json_data = json.loads(data)</span><br><span class="line">    name = json_data[<span class="string">'name'</span>]</span><br><span class="line"><span class="keyword">except</span> json.JSONDecodeError <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'JSONDecodeError 异常:'</span>, e)</span><br><span class="line"><span class="keyword">except</span> KeyError <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'KeyError 异常:'</span>, e)</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'其他异常:'</span>, e)</span><br></pre></td></tr></table></figure>

<p>这种写法的好处是，你可以在不同的捕获异常代码块中单独去写针对特定异常的处理逻辑。如果首先抛出了 <code>json.JSONDecodeError</code> 异常，那么之后的 <code>except</code> 就不会被执行了，这有点像 <code>if ... else ...</code> 的逻辑。可以看到代码的最后还加上了 <code>Exception</code> 异常类的捕获，这也是推荐的做法，因为假使程序没能如预期的抛出 <code>json.JSONDecodeError</code> 或者 <code>KeyError</code> 异常，最后还是会有一个兜底的 <code>Exception</code> 异常捕获，这样就不至于因为未知的异常而终止程序。</p>
<p>异常捕获还可以有更简洁的写法：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    print(<span class="string">'try 代码块开始执行'</span>)</span><br><span class="line">    <span class="number">1</span> / <span class="number">0</span></span><br><span class="line">    print(<span class="string">'try 代码块执行完毕'</span>)</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    print(<span class="string">'出现了异常'</span>)</span><br></pre></td></tr></table></figure>

<p>这样写能够捕获任何异常，不过，通常并不建议这样做，因为在 <code>except</code> 代码块中你并不知道到底产生了哪种异常，而实际工作中，你往往需要在出现异常的地方记录日志，就需要知道是产生了哪种异常。</p>
<p>还有一种 <code>try ... finally</code> 的形式的写法也是可以的。通常用于不关心程序是否报错，但程序占用的资源无论如何最终都需要释放的时候。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = open(<span class="string">'a.txt'</span>, <span class="string">'w'</span>)</span><br><span class="line">    <span class="comment"># do something</span></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    f.close()</span><br></pre></td></tr></table></figure>

<p>其实我们使用的 <code>with open</code> 语句底层原理大概就是这样实现的。</p>
<h3 id="自定义异常"><a href="#自定义异常" class="headerlink" title="自定义异常"></a>自定义异常</h3><p>如果你观察的比较仔细，就会发现，上面的例子中出现的 <code>JSONDecodeError</code> 异常并不在文章开头所列的 Python 内置异常类中。事实上，它是 <code>json</code> 模块中定义的一个异常类。根据这个启发，你应该能猜到，其实 Python 是允许我们定义自己的异常类的。</p>
<p>下面就是一个自定义异常类的示例：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    print(<span class="number">1</span>)</span><br><span class="line">    <span class="keyword">raise</span> MyException(<span class="string">'自定义异常'</span>)</span><br><span class="line">    print(<span class="number">2</span>)</span><br><span class="line"><span class="keyword">except</span> MyException <span class="keyword">as</span> e:</span><br><span class="line">    print(e)</span><br></pre></td></tr></table></figure>

<p>代码执行结果如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">1</span><br><span class="line">自定义异常</span><br></pre></td></tr></table></figure>

<p>自定义异常类也非常简单，我们只需要定一个类继承 <code>Exception</code> 类即可，你甚至不需要写其他任何代码。</p>
<p>实际上，自定义异常类可以继承任何 Python 中内置的异常类，但更推荐的继承类就是 <code>Exception</code>，虽然 <code>BaseException</code> 才是所有异常类的顶层类，并且能捕获更多的异常。但它会将 <code>KeyboardInterrupt</code> 异常捕获到，<code>KeyboardInterrupt</code> 异常通常由 <code>Ctrl + C</code> 来触发，而触发 <code>Ctrl + C</code> 时往往是我们需要主动退出程序，应该让 Python 解释器正常抛出这个异常才对。</p>
<h3 id="异常处理时可能会遇到的问题"><a href="#异常处理时可能会遇到的问题" class="headerlink" title="异常处理时可能会遇到的问题"></a>异常处理时可能会遇到的问题</h3><p>在异常处理过程中，你可能会遇到一些不太常见的问题。</p>
<p>假如在一个函数中处理异常，如果 <code>try</code> 代码块中有 <code>return</code> 语句，那么 <code>finally</code> 语句是否还会执行呢？</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line">count = <span class="number">1</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">global</span> count</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        print(<span class="string">'try'</span>)</span><br><span class="line">        <span class="keyword">return</span> count</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        print(<span class="string">'except'</span>)</span><br><span class="line">        print(e)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'finally'</span>)</span><br><span class="line">        count += <span class="number">1</span></span><br><span class="line"></span><br><span class="line">result = foo()</span><br><span class="line">print(result)</span><br><span class="line">print(count)</span><br></pre></td></tr></table></figure>

<p>代码执行结果如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">try</span><br><span class="line">finally</span><br><span class="line">1</span><br><span class="line">2</span><br></pre></td></tr></table></figure>

<p>由代码执行结果可以看出，<code>return</code> 语句实际上是在 <code>finally</code> 语句执行之前执行的，不过，<code>return</code> 的结果是要等到执行完 <code>finally</code> 代码块内的语句之后才返回的。所以在函数外部打印的 <code>result</code> 结果为 <code>1</code>，<code>count</code> 结果最终变为了 <code>2</code>。</p>
<p>再看一个关于变量名和 <code>Exception</code> 别名出现同名的情况下，会产生什么结果。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">e = <span class="number">0</span></span><br><span class="line"></span><br><span class="line">print(e)  <span class="comment"># 0</span></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span> / <span class="number">0</span></span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'捕获异常:'</span>, e)  <span class="comment"># 捕获异常: division by zero</span></span><br><span class="line"></span><br><span class="line">print(e)  <span class="comment"># NameError: name 'e' is not defined</span></span><br></pre></td></tr></table></figure>

<p>代码执行结果如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">0</span><br><span class="line">捕获异常: division by zero</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;demo.py&quot;, line 9, in &lt;module&gt;</span><br><span class="line">    print(e)</span><br><span class="line">NameError: name &#39;e&#39; is not defined</span><br></pre></td></tr></table></figure>

<p>我们在最开始定义了一个变量 <code>e = 0</code>，并且在 <code>except Exception as e:</code> 时同样将 <code>Exception</code> 的别名定义成了 <code>e</code>。最终的现象是，在 <code>except</code> 代码块中可以使用这个变量，而 <code>except</code> 代码块执行完成以后，再次打印 <code>e</code> 变量就抛出了 <code>NameError</code> 异常，异常信息提示 <code>e</code> 没有定义。</p>
<p>实际上，出现这个问题的原因 <a href="https://docs.python.org/3/reference/compound_stmts.html#the-try-statement" target="_blank" rel="noopener">Python 官方文档</a> 已有说明。</p>
<p>以上处理异常的代码其实相当于：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">e = <span class="number">0</span></span><br><span class="line"></span><br><span class="line">print(e)</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span> / <span class="number">0</span></span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        print(<span class="string">'捕获异常:'</span>, e)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        <span class="keyword">del</span> e</span><br><span class="line"></span><br><span class="line">print(e)</span><br></pre></td></tr></table></figure>

<p>在每次执行了 <code>except</code> 代码块的最后，Python 解释器都会自动删除掉异常类的别名，所以在 <code>except</code> 代码块的外面再次打印 <code>e</code> 时，抛出了 <code>NameError</code> 异常。</p>

        </div>

        <blockquote class="post-copyright">
    
    <div class="content">
        
<span class="post-time">
    最后更新时间：<time datetime="2022-12-24T13:16:45.345Z" itemprop="dateUpdated">2022-12-24 21:16:45</time>
</span><br>


        
        <a href="/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/" target="_blank" rel="external">http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/</a>
        
    </div>
    
    <footer>
        <a href="http://www.jianghushinian.cn">
            <img src="/img/avatar.png" alt="江湖十年">
            江湖十年
        </a>
    </footer>
</blockquote>

        


        <div class="post-footer">
            
	<ul class="article-tag-list" itemprop="keywords"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/Python/" rel="tag">Python</a></li></ul>


            
<div class="page-share-wrap">
    

<div class="page-share" id="pageShare">
    <ul class="reset share-icons">
      <li>
        <a class="weibo share-sns" target="_blank" href="http://service.weibo.com/share/share.php?url=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/&title=《Python 异常处理机制》 — 江湖十年&pic=http://www.jianghushinian.cn/img/avatar.png" data-title="微博">
          <i class="icon icon-weibo"></i>
        </a>
      </li>
      <li>
        <a class="weixin share-sns wxFab" href="javascript:;" data-title="微信">
          <i class="icon icon-weixin"></i>
        </a>
      </li>
      <li>
        <a class="qq share-sns" target="_blank" href="http://connect.qq.com/widget/shareqq/index.html?url=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/&title=《Python 异常处理机制》 — 江湖十年&source=Python 解释器在执行代码时，如果发生错误，解释器会立即抛出异常并终止程序的运行。异常处理，实际上就是一种错误处理机制。" data-title=" QQ">
          <i class="icon icon-qq"></i>
        </a>
      </li>
      <li>
        <a class="facebook share-sns" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/" data-title=" Facebook">
          <i class="icon icon-facebook"></i>
        </a>
      </li>
      <li>
        <a class="twitter share-sns" target="_blank" href="https://twitter.com/intent/tweet?text=《Python 异常处理机制》 — 江湖十年&url=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/&via=http://www.jianghushinian.cn" data-title=" Twitter">
          <i class="icon icon-twitter"></i>
        </a>
      </li>
      <li>
        <a class="google share-sns" target="_blank" href="https://plus.google.com/share?url=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/" data-title=" Google+">
          <i class="icon icon-google-plus"></i>
        </a>
      </li>
    </ul>
 </div>



    <a href="javascript:;" id="shareFab" class="page-share-fab waves-effect waves-circle">
        <i class="icon icon-share-alt icon-lg"></i>
    </a>
</div>



        </div>
    </div>

    
<nav class="post-nav flex-row flex-justify-between">
  
    <div class="waves-block waves-effect prev">
      <a href="/2019/09/18/Python-%E4%B8%8A%E4%B8%8B%E6%96%87%E7%AE%A1%E7%90%86%E5%99%A8%E5%AE%9E%E7%8E%B0/" id="post-prev" class="post-nav-link">
        <div class="tips"><i class="icon icon-angle-left icon-lg icon-pr"></i> Prev</div>
        <h4 class="title">Python 上下文管理器实现</h4>
      </a>
    </div>
  

  
    <div class="waves-block waves-effect next">
      <a href="/2019/09/15/Python-%E5%8F%AF%E5%8F%98%E7%B1%BB%E5%9E%8B%E4%BD%9C%E4%B8%BA%E5%87%BD%E6%95%B0%E9%BB%98%E8%AE%A4%E5%8F%82%E6%95%B0%E6%97%B6%E7%9A%84%E5%89%AF%E4%BD%9C%E7%94%A8/" id="post-next" class="post-nav-link">
        <div class="tips">Next <i class="icon icon-angle-right icon-lg icon-pl"></i></div>
        <h4 class="title">Python 可变类型作为函数默认参数时的副作用</h4>
      </a>
    </div>
  
</nav>



    

















<section class="comments" id="comments">
    <div id="gitalk-container"></div>
    <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
    <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
    <script src="/js/md5.min.js"></script>
    <script>
        var id = location.pathname
        if (location.pathname.length > 50) {
          id = location.pathname.replace(/\/\d+\/\d+\/\d+\//, '').replace('/', '').substring(0, 50)
        }
        const gitalk = new Gitalk({
          clientID: '9d22aca5e6d2962ef86e',
          clientSecret: '4a93d756cc14be84e76817cacbf8533fe424f1ae',
          repo: 'https://github.com/jianghushinian/jianghushinian.github.io',
          owner: 'jianghushinian',
          admin: ['jianghushinian'],
          id: md5(id),      // Ensure uniqueness and length less than 50，使用 md5 保证字符长度小于 50
          title: document.title.split('|')[0],
          distractionFreeMode: false  // Facebook-like distraction free mode
        })

        gitalk.render('gitalk-container')
    </script>
</section>




</article>



</div>

        <footer class="footer">
    <div class="top">
        
<p>
    <span id="busuanzi_container_site_uv" style='display:none'>
        <span id="busuanzi_value_site_uv"></span>
    </span>
    <span id="busuanzi_container_site_pv" style='display:none'>
        <span id="busuanzi_value_site_pv"></span>
    </span>
</p>


        <p>
            
                <span><a href="/atom.xml" target="_blank" class="rss" title="rss"><i class="icon icon-lg icon-rss"></i></a></span>
            
            <span>博客内容遵循 <a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">知识共享 署名 - 非商业性 - 相同方式共享 4.0 国际协议</a></span>
        </p>
    </div>
    <div class="bottom">
        <p><span>江湖十年 &copy; 2019 - 2022</span>
            <span>
                
                Power by <a href="http://hexo.io/" target="_blank">Hexo</a> Theme <a href="https://github.com/yscoder/hexo-theme-indigo" target="_blank">indigo</a>
            </span>
        </p>
    </div>
</footer>

    </main>
    <div class="mask" id="mask"></div>
<a href="javascript:;" id="gotop" class="waves-effect waves-circle waves-light"><span class="icon icon-lg icon-chevron-up"></span></a>



<div class="global-share" id="globalShare">
    <ul class="reset share-icons">
      <li>
        <a class="weibo share-sns" target="_blank" href="http://service.weibo.com/share/share.php?url=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/&title=《Python 异常处理机制》 — 江湖十年&pic=http://www.jianghushinian.cn/img/avatar.png" data-title="微博">
          <i class="icon icon-weibo"></i>
        </a>
      </li>
      <li>
        <a class="weixin share-sns wxFab" href="javascript:;" data-title="微信">
          <i class="icon icon-weixin"></i>
        </a>
      </li>
      <li>
        <a class="qq share-sns" target="_blank" href="http://connect.qq.com/widget/shareqq/index.html?url=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/&title=《Python 异常处理机制》 — 江湖十年&source=Python 解释器在执行代码时，如果发生错误，解释器会立即抛出异常并终止程序的运行。异常处理，实际上就是一种错误处理机制。" data-title=" QQ">
          <i class="icon icon-qq"></i>
        </a>
      </li>
      <li>
        <a class="facebook share-sns" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/" data-title=" Facebook">
          <i class="icon icon-facebook"></i>
        </a>
      </li>
      <li>
        <a class="twitter share-sns" target="_blank" href="https://twitter.com/intent/tweet?text=《Python 异常处理机制》 — 江湖十年&url=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/&via=http://www.jianghushinian.cn" data-title=" Twitter">
          <i class="icon icon-twitter"></i>
        </a>
      </li>
      <li>
        <a class="google share-sns" target="_blank" href="https://plus.google.com/share?url=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/" data-title=" Google+">
          <i class="icon icon-google-plus"></i>
        </a>
      </li>
    </ul>
 </div>


<div class="page-modal wx-share" id="wxShare">
    <a class="close" href="javascript:;"><i class="icon icon-close"></i></a>
    <p>扫一扫，分享到微信</p>
    <img src="//api.qrserver.com/v1/create-qr-code/?data=http://www.jianghushinian.cn/2019/09/16/Python-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6/" alt="微信分享二维码">
</div>




    <script src="//cdn.bootcss.com/node-waves/0.7.4/waves.min.js"></script>
<script>
var BLOG = { ROOT: '/', SHARE: true, REWARD: false };


</script>

<script src="//unpkg.com/hexo-theme-material-indigo@latest/js/main.min.js"></script>


<div class="search-panel" id="search-panel">
    <ul class="search-result" id="search-result"></ul>
</div>
<template id="search-tpl">
<li class="item">
    <a href="{path}" class="waves-block waves-effect">
        <div class="title ellipsis" title="{title}">{title}</div>
        <div class="flex-row flex-middle">
            <div class="tags ellipsis">
                {tags}
            </div>
            <time class="flex-col time">{date}</time>
        </div>
    </a>
</li>
</template>

<script src="//unpkg.com/hexo-theme-material-indigo@latest/js/search.min.js" async></script>






<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>





</body>
</html>
